-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', GENDER, COUNT(DISTINCT o.USER_ID) AS 'USERS'
FROM ONLINE_SALE o JOIN USER_INFO u ON  o.USER_ID = u.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3