-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, P.PRICE * SUM(o.AMOUNT) AS 'TOTAL_SALES'
FROM FOOD_PRODUCT p JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05-%'
GROUP BY 1
ORDER BY 3 DESC, 1