-- 코드를 입력하세요
SELECT DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h JOIN CAR_RENTAL_COMPANY_CAR c
ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = '세단'
AND h.START_DATE LIKE '%-10-%'
ORDER BY 1 DESC